export const SCORING_WEIGHTS = {
  REQUIRED_SKILLS: 30,
  PREFERRED_SKILLS: 10,
  TOOLS: 10,
  EXPERIENCE: 25,
  EDUCATION: 15,
  ELIGIBILITY: 10,
  JOB_REALITY: 0,
  COMPETITION: 0,
} as const;

export const DECISION_THRESHOLDS = {
  APPLY: 75,
  APPLY_WITH_IMPROVEMENTS: 55,
  IMPROVE: 35,
  // Below 35 is SKIP
} as const;
